name: E2E tests for MeshSync

on:
    push:
      branches:
        - "*"   
    pull_request:
      branches:
        - "*"
jobs: 
  e2e-test:
    name: End to End
    runs-on: ubuntu-22.04
    strategy: 
      fail-fast: false
      matrix:
        k8s_version: ['v1.27.3']
        platform: ['docker', 'kubernetes']

    steps: 
      - name: Setup Kubernetes
        uses: manusa/actions-setup-minikube@v2.7.2
        with: 
          minikube version: 'v1.30.1'
          kubernetes version: ${{matrix.k8s_version}}
          driver: docker

      - name: Run minikube tunnel
        run: | 
          echo 'Running minikube tunnel'
          minikube tunnel $> /dev/null &
        shell: bash

      - name: Checkout Code
        uses: actions/checkout@master
      
      - name: Set Up Nats
        run: |
          sudo apt install zip
          curl -L https://github.com/nats-io/nats-server/releases/download/vX.Y.Z/nats-server-v2.10.7-linux-amd64.zip -o nats-server.zip
          unzip nats-server.zip -d nats-server
          sudo cp nats-server/nats-server-2.10.7-linux-amd64/nats-server /usr/local/bin
          nats-server --version
      - name: Start nats server
        run: |
          

      - name: Setup nats-cli
        run: |
          curl -sf https://binaries.nats.dev/nats-io/natscli/nats@latest | bash
          nats --version

      - name: Setup Go
        uses: actions/setup-go@master
        with:
            go-version: "1.21"        
            
      - name: Run MeshSync
        run: |
          go run main.go

      - name: Subscribe messages
        run: |
          echo | nats -sub meshery.meshsync.core --count 10
            #deploy meshsync
      #test publishing


